#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-deployment
  template:
    metadata:
      labels:
        app: application-deployment
    spec:
      containers:
        - name: main
          image: {{APP_IMAGE}}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 22
          envFrom:
            - configMapRef:
                name: app-fabric-org1-v1-map
          resources:
            requests:
              memory: "50Mi"
              cpu: "0.1"
          volumeMounts:
            - name: fabricids
              mountPath: /fabric/application/wallet
            - name: fabric-ccp
              mountPath: /fabric/application/gateway
            - name: tlscerts
              mountPath: /fabric/tlscacerts
            - name: cacerts
              mountPath: /fabric/cacerts
            - name: app-codebase
              mountPath: /app
        - name: redis
          image: {{REDIS_IMAGE}}
          ports:
            - containerPort: 6379
      volumes:
        - name: app-codebase
          hostPath:
            path: /test-network-k8s/application/document_notarization
        - name: fabric-ccp
          configMap:
            name: app-fabric-ccp-v1-map
        - name: fabricids
          configMap:
            name: app-fabric-ids-v1-map
        - name: tlscerts
          configMap:
            name: app-fabric-tls-v1-map
        - name: cacerts
          configMap:
            name: app-fabric-org1-cacerts-v1-map

---
apiVersion: v1
kind: Service
metadata:
  name: application-deployment
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
    - name: ssh
      port: 22
      protocol: TCP
  selector:
    app: application-deployment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-deployment
spec:
  rules:
    - http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: application-deployment
                port:
                  number: 3000
#          - path: "/ssh"
#            pathType: Prefix
#            backend:
#              service:
#                name: application-deployment
#                port:
#                  number: 22